### ISSUE TITLE
Annotate tree edges with AA mutations

### ISSUE THREAD

**Issue by lauradoepker** [matsengrp/cft#159]
At Cassie's Overbaugh lab meeting today, @psathyrella and @krdav helped us conclude that it would be helpful to view trees that are collapsed to differences in amino acids.  I'm not clear on if it would be easier to just build amino acid-based trees from the partis clusters or, as @krdav explained today, perhaps some of the nodes/branches could be collapsed based on same or different amino acid sequence.  This would cut down on the bushiness of these trees within our clonal families of interest.

On our end, we need to know about the Ab evolution (which is nt based), but we only care about actually generation different Ab amino acid sequences.

**Comment by metasoarous** [comment]
Issue moved to [matsengrp/olmsted #133](https://github.com/matsengrp/olmsted/issues/133) via [**ZenHub**](https://www.zenhub.com/)
