### ISSUE TITLE
clustering summary information

### ISSUE THREAD

**Issue by psathyrella** [matsengrp/cft#16]
reminder from meeting with erick, who presumably will want to rewrite this issue.

**Comment by metasoarous** [comment]
@lauradoepker @psathyrella @matsen Thoughts on where we're at with this issue? Should we consider this done? If not, what's the course forward?

**Comment by psathyrella** [comment]
I don't have anything else I want to happen here.

**Comment by metasoarous** [comment]
Hey @lauradoepker; If there's nothing else needed here, I'm going to go ahead and close this.
