### ISSUE TITLE
Dot labeling for different antibody clusters

### ISSUE THREAD

**Issue by lauradoepker** [matsengrp/cft#164]
@metasoarous 

Hi there - Megan (again) from Laura's account with a new question.

- Can we change the trees so that they have consistent labeling between different antibody clusters? As the trees stand right now the same colors of dots represent different timepoints among the different antibodies. i.e. For QA255.105VH's clusters, orange dots represent timepoint 462dpi and there is no 1512dpi timepoint data available. However, if you jump over to any of the clusters for QA255.157VK the orange dots now represent the 1512dpi timepoint and yellow dots now represent the 462dpi.

Let me know if that doesn't make sense.

Thanks!
Megan

**Comment by metasoarous** [comment]
Closing in favor of matsengrp/olmsted#89 ^ since this is really an Olmsted issue.
