### ISSUE TITLE
Improve regular pruning strategy

### ISSUE THREAD

**Issue by metasoarous** [matsengrp/cft#172]
Our present tree pruning strategy only looks at distance between seed lineage and the sequences selected. There is nothing that necessarily ensures this will give us a nuanced view of the diversity along the lineage. 

Imagine a tree that looks like this:

![selection_031](https://cloud.githubusercontent.com/assets/88556/25594641/4841279e-2e76-11e7-95a9-56e51b2aa4f2.png)

I'd really rather have nodes a, b & c and perhaps one or two of those in X. But the way we do things presently we might only pick sequences from X. 

It seems like we need to do something roughly along the lines of taking each of the seed lineage's internal nodes and proportionally sampling their descendants in order of proximity to seed lineage. A nice feature of this is that it would also generalize naturally towards the few situations where we see two seeds falling in the same cluster:

![selection_033](https://cloud.githubusercontent.com/assets/88556/25600218/78393fd8-2e97-11e7-8cb9-b09e9caa0a94.png)

I could imagine a more formal and general treatment of the problem in terms of the work of moving mass through the tree towards the lineage, or some such. And perhaps there's some interesting analysis that could be done in this vein as well, e.g. testing for correlation of mass and diversity distribution along a lineage to the corresponding seed's binding affinity?

**Comment by matsen** [comment]
It seems to me that pruning is going to be a lot less important moving forward with UMIs. @lauradoepker let me know if you disagree. 

Closing, but feel free to re-open.
