### ISSUE TITLE
Alignment overview

### ISSUE THREAD

**Issue by matsen** [matsengrp/cft#175]
Hey folks-- as I've been poking around with @lauranoges sequences, I've found it useful to look at a zoomed-out view of a multiple sequence alignment of the clonal family sequences before any trimming or pruning. Here's the view of the BF520.1-k-IgH family:
![bf520-k-igh align](https://user-images.githubusercontent.com/112708/27687862-5ceada2e-5c8d-11e7-93b9-1c0cb22e2a29.png)

In this case, we see one sequence with a quite surprisingly big insertion in the V, which seems like it might be some sort of preprocessing error? I didn't think that we were getting reads that long. In any case looking at data is a good thing.

Does this seem useful, Laura? Please say if "meh".

If so, it just needs two steps:

* making a multiple sequence alignment of the original sequences
* running [seqs2png](https://gist.github.com/matsen/a28a737269552a2a022a)

The blocks representing the MSA bases can be made bigger and smaller. It's currently 3x3 by default.

**Comment by matsen** [comment]
Although it seems useful to do something with minimally-processed sequences, I don't see how this would fit into our current Olmsted world, so I suggest closing.

**Comment by metasoarous** [comment]
We could still include this in the core cft pipeline so that the targets are there for folks to poke around at if an issue comes up with a cluster.
