### ISSUE TITLE
smarter selection of parsimony tree

### ISSUE THREAD

**Issue by WSDeWitt** [matsengrp/cft#176]
`dnapars` generally outputs severally degenerately optimal trees. The current `process_asr.py` script parses the `dnapars` output, but only takes the first tree it finds. We have ideas for resolving parsimony degeneracy (like with motif likelihoods), so `process_asr.py` needs to be updated to parse the full list of trees, and select one (initially just the arbitrary first one, but later something smarter like motif ML tree).

**Comment by metasoarous** [comment]
I'm not sure what happened on this issue, but I think it was some combination of deciding with Laura that the ML trees were doing what we wanted them to (after fixing some tree viz quirkiness with the old ete3 rendering system), and other work taking priority. In any case, just checking in here to see if this is something which we want to resurrect, or whether we want to focus on custom phylogenetic methods, or seeing if we can't get some other tree program to do what we want it to.

@matsen Thoughts on this?

**Comment by matsen** [comment]
We don't use parsimony for anything any more, right? If not, I think we can close.

**Comment by metasoarous** [comment]
Correct, we are not.
