### ISSUE TITLE
Refinement of minadcl?

### ISSUE THREAD

**Issue by metasoarous** [matsengrp/cft#182]
It occurred to me that if we believe that sequences with higher duplicity are less likely to be the result of sequencing error, then perhaps we should take this into account as we select representatives.

@matsen How crazy do you think it would be to adapt `min_adcl` to accept weights? Based on my intuitive understanding of what `min_adcl` is doing, it seems like that could be translated into a well defined objective function. But I'm not sure how easy it would be to adapt the current implementation to account for that information. Tell me if this is just way out of scope :-)

On the other hand, I _imagine_ that if `min_adcl` is doing what we expect it to, it might actually be doing a decent job of picking out sequences of higher duplicity. I'd expect such sequences to tend to be in the "center" of sequencing error point mutations, as well as genuine biological sequences of lower fitness branching off these centers.

Now that I'm working on figuring out the clusters for `min_adcl` for the purpose of aggregating duplicity, we could actually start looking at whether we tend to pick up higher duplicity sequences. I'd imagine that demonstrating such a tendancy might boost confidence in our methods.

I recognize that this isn't super high in priority right now, but I wanted to jot down the thought while it was on my mind.

**Comment by matsen** [comment]
Is this still interesting? My sense is that minadcl isn't really used for much other than display, as the ancestral sequence lineage information is the most important, and that doesn't use adcl atall.

**Comment by lauradoepker** [comment]
Closing because Erick's comment is correct in that we only use this for unseeded partis visualization

**Comment by metasoarous** [comment]
This seemed interesting to theoretically when we started thinking about it, but we agreed that it wasn't really a pressing issue and so it's just been sitting here. Happy to leave closed to clear up the board space.
