### ISSUE TITLE
Add alternate x/y scales

### ISSUE THREAD

**Issue by metasoarous** [matsengrp/cft#260]
Should be able to do a log scale to avoid points clumping up along an axis like this

![image](https://user-images.githubusercontent.com/88556/51017161-e6b46280-1527-11e9-95fd-f71db187c4a1.png)

**Comment by eharkins** [comment]
Should this be in Olmsted?

**Comment by metasoarous** [comment]
Issue moved to [matsengrp/olmsted #122](https://github.com/matsengrp/olmsted/issues/122) via [**ZenHub**](https://www.zenhub.com/)

**Comment by metasoarous** [comment]
Issue moved to [matsengrp/olmsted #123](https://github.com/matsengrp/olmsted/issues/123) via [**ZenHub**](https://www.zenhub.com/)
