### ISSUE TITLE
Add version of `n_seqs` summing over multiplicity data

### ISSUE THREAD

**Issue by metasoarous** [matsengrp/cft#263]
Not sure how I hadn't thought of this before, but we should perhaps be looking at sum of the multiplicities of all the input data instead of just the number of unique sequences going into partis. It's debatable how interpret-able this value is, but in conjunction with current `n_seqs` count, I think it provides useful data.

**Comment by metasoarous** [comment]
@eharkins If you're looking for something to work on cft-side, this is a good issue to tackle.

**Comment by eharkins** [comment]
@metasoarous Should we add one for `cluster_multiplicity` as well?

**Comment by metasoarous** [comment]
Cluster multiplicity already takes this into account.

**Comment by eharkins** [comment]
@metasoarous 
> Cluster multiplicity already takes this into account.

Takes what into account?

**Comment by metasoarous** [comment]
LOL. We may be talking past each other...

Cluster multiplicity already aggregates over input multiplicity (based on raw identity of read sequences) and partis multiplicity (based on identity of sequences once trimmed to the "region of interest" by partis).

To answer your other question about the issue at hand, this should happen at the cluster/clonal-family level.

**Comment by eharkins** [comment]
@metasoarous 
As far as I can tell from your comments here and on slack:
- we would like to add a metric at the cluster/CF level that adds up `multiplicity` for each sequence in the cluster/CF
- I can do this in `merge_upstream_seqmeta` by changing the return type so it's no longer returning a generator
- we _don't_ want (and it apparently wouldn't make sense) to add a metric like the one we are talking about here that sums over the `cluster_multipilcity` of each sequence. I am still not clear because while cluster multiplicity aggregates over upstream mults, it is a per-sequence metric and is not ever summed up over the whole cluster (as far as I can tell) in the way we are discussing for `multiplicity`. That is what I was suggesting but maybe it wouldn't make sense if it wouldn't represent unique information from the sum of all pure `multiplicity`s in the cluster that we are adding.

Any name suggestions for the new metric? `n_seqs_multiplicity` or  `n_seqs_upstream` or `total_multiplicity` or something like that?

**Comment by eharkins** [comment]
https://github.com/matsengrp/cft/tree/263-n-seqs-mult

**Comment by metasoarous** [comment]
First off, this code looks great. However, I don't like the name, and think we should either:
* rename `n_seqs_multiplicity` -> `n_seqs` and `n_seqs` (as currently defined) to something like `n_distinct_seqs`
* use `n_seqs` as currently defined, and `n_reads` for the version including read multiplicity

I'm kind of leaning towards the latter, but am open to feedback on this. CC @lauradoepker @psathyrella?

As far as your question about `cluster_multiplicity`, I realize now that I misunderstood what you were asking previously. Yes, we could in theory sum over the `cluster_multiplicity` for each of the sequences in the minadcl pruned reconstructions, which should come out to the same number as what you compute in your branch above. However, it's a little messier having to do this at the reconstruction level (even though in theory it would be less "work" since there would be fewer numbers to add up this way).

**Comment by eharkins** [comment]
After chatting with @metasoarous, we won't concern ourselves with summing over cluster multiplicity for now.

**Comment by eharkins** [comment]
@metasoarous I'd like to merge this. Are we down to the naming? I guess it's important given: https://github.com/matsengrp/olmsted/commit/55608edfa8765692b6bd6e26b348cbab10616e35#r32639860
So,
* `n_seqs`, ` n_distinct_seqs`: 
** pro: the concept of "distinct" makes sense to me intuitively in the context of the two names (one is distinct and one includes duplicates)
** con: might not be intuitive depending on one's concept of multiplicity / aggregation WRT sequences in a clonal family
* `n_seqs`, `n_reads`:
** pro: more explicitly separates the two
** con: maybe less clear the relationship between them?

Fine with the second one if that's what you prefer

**Comment by metasoarous** [comment]
I'm leaning towards the latter, in part because it means less work renaming things in cft. But really we should let this come down to whichever makes more sense semantically, work be damned. I _think_ the second option is more semantically clear as well, but I'd like to get feedback on this from @psathyrella and especially @lauradoepker.

**Comment by lauradoepker** [comment]
I'm a bit lost here, but I gather that this is referring to a single clonal family?  The `n-seqs` in the family?  Would `n_distinct_seqs` = unique sequences in the family? Would `n_reads` = number of total reads for all sequences in the family, unique or not?  These sound like very different things to me, so I presume I'm confused. @metasoarous

**Comment by psathyrella** [comment]
@lauradoepker i'm also confused, but i think it's just keeping track of multiplicity, i.e. in the first option n_seqs would be the total number of sequences, and n_distinct_seqs would be the total number of distinct sequences.

But, yeah, the fact we're both confused i think means neither of the options are a good idea. In particular i think calling variable A the general term, and variable B a variation on that whose existence casts doubt on what variable  A actually is tends to end badly. Before i suggest anything, are the first and second options switching which of the two numbers is n_seqs? cause n_reads should be the larger of them, right?

If i'm halfway understanding what the numbers are, I would say something like n_total_reads and n_unique_seqs (distinct is ok, but I think 'unique' is more common both in our code and in other people's). It's just so much less work in the long run to name it so you don't have to spend a bunch of time explaining it (and forgetting which is which yourself down the road).

**Comment by eharkins** [comment]
@lauradoepker 
> The n-seqs in the family? Would n_distinct_seqs = unique sequences in the family? 

Yes

> Would n_reads = number of total reads for all sequences in the family, unique or not? 

It would be "number of total reads [in the sample] for all sequences in the family, unique or not". Yes

> These sound like very different things to me

They are, which is why it's important they are named distinctly and clearly, sorry to be confusing!

@psathyrella 
> it's just keeping track of multiplicity, i.e. in the first option n_seqs would be the total number of sequences, and n_distinct_seqs would be the total number of distinct sequences.

Yes

> calling variable A the general term, and variable B a variation on that whose existence casts doubt on what variable A actually is tends to end badly. 

Makes sense!

> are the first and second options switching which of the two numbers is n_seqs? cause n_reads should be the larger of them, right?

Yes, since n_reads accounts for multiplicity / multiple reads of the same sequence.

> n_total_reads and n_unique_seqs

Works for me! @metasoarous?

**Comment by metasoarous** [comment]
`n_total_reads` and `n_unique_seqs` certainly seems clearer to me. I'm all for it if everyone else agrees. @lauradoepker?

**Comment by lauradoepker** [comment]
Yes, good

**Comment by eharkins** [comment]
We will want to change all the places that Olmsted expects `n_seqs` to `n_unique_seqs` as well as add `n_total_reads`, including in the new, generalized process_data.py script. Not doing this quite yet so we can continue to use old cft built data for now.

**Comment by eharkins** [comment]
https://github.com/matsengrp/cft/compare/6e6b035f59e8...8c84fc01a4ab
