### ISSUE TITLE
Create logo plot from partis alternative naives

### ISSUE THREAD

**Issue by eharkins** [matsengrp/cft#266]
@lauradoepker would like to visualize the uncertainty associated with partis alternative naive sequences, using their estimated probabilities. This will be a logo plot where the size of the amino acid character at the site represents the estimated probability of that character among the partis alternative naives.

**Comment by eharkins** [comment]
https://github.com/matsengrp/cft/tree/266-partis-alt-naive-logos

**Comment by eharkins** [comment]
@lauradoepker Let me know how they look since I added the cdr3 plots and a different color scheme. Will close this if all good :)

**Comment by metasoarous** [comment]
Hey @lauradoepker. Just checking in to see if you've had a chance to look at this yet. @eharkins and I are trying to close out old issues, so please let us know if you have any questions or concerns on this before we close. Thanks!

**Comment by lauradoepker** [comment]
Yes, I have.  Nothing needed at the moment - feel free to close. @metasoarous @eharkins
