### ISSUE TITLE
Olmsted frozen deployments

### ISSUE THREAD

**Issue by matsen** [matsengrp/cft#283]
Current subjects:

* QA013.2
* MG505 and QA255

**Comment by lauradoepker** [comment]
For MG505, I'm interested in:
`/fh/fast/matsen_e/processed-data/partis/mg505-synth/v20`

For QA255, I'm interested in:
`/fh/fast/matsen_e/processed-data/partis/qa255-synth/v18`
`/fh/fast/matsen_e/processed-data/partis/qa255-synth/v19`
`/fh/fast/matsen_e/processed-data/partis/qa255-synth/no-indels`

For QA103, Mackenzie is interested in:
`/fh/fast/matsen_e/processed-data/partis/qa013-mar-8/v19`
`/fh/fast/matsen_e/processed-data/partis/qa013-synth/v19`

**Comment by eharkins** [comment]
Should have said this earlier, but this should be a https://github.com/matsengrp/olmsted issue. However, do we want to have this same concept for freezing CFT (since it is doing the analyses we see on Olmsted)?

**Comment by lauradoepker** [comment]
Yes, same concept.  I don't care in which repo this issue sits @eharkins 🤷‍♀

**Comment by eharkins** [comment]
They should each have their own since they are distinct parts of the larger goal. Though cft might not need this issue at all so long as we record which metadata.json (cft output summary) we are processing in Olmsted, since those files contain a cft commit.
