### ISSUE TITLE
Flow chart defining correspondence between Overbaugh and Matsen teams on B-cell research

### ISSUE THREAD

**Issue by eharkins** [matsengrp/cft#294]
In the recent past, we have talked about the importance of erring on the side of having conversations in the same room with one another when there is any uncertainty about how to proceed with or interpret some software or results.

@lauradoepker and @mmshipley and I talked about the idea of having this be explicitly outlined (e.g. in a flow chart) so that we have some general set of guidelines for when we should pause and meet about something before proceeding with an analysis. 

If we do this, it would be important to:

- include some catch all that was effectively: 
> erring on the side of having conversations in the same room with one another when there is any uncertainty about how to proceed with or interpret some software or results

- reference steps in the pipeline start to finish (sequencing to antibody lineages).

- reference example file paths for output to use for a given step (or say so if making an assumption about a file path for a given step is a bad idea)

- design and update it in a way such that it did not get out of date or serve as a substitute for times when we really should meet about something.

Thoughts on this @psathyrella @matsen?

**Comment by matsen** [comment]
I love this. Yes.

I would be quite happy for you all to just figure out on your own whatever system works for you. 

Not that you asked, but... if I was going to do something like this for myself, I'd have every analysis be an issue. The text of the issue would contain a list of files/information required to do an analysis. Once a CFT or whatever run is done, there is a comment on that issue which describes which files satisfy the needs specified in the issue text. Once everyone approves that those files are current and useful for addressing the need (perhaps in an in-person meeting), then the issue moves to the next stage (like in a Project table). 

I think that some textual representation of what files are being used would be useful, and a good record.

Again, you all do what is best for you. I'm just in the peanut gallery.

**Comment by eharkins** [comment]
@matsen what we discussed was more an abstract set of guidelines, but something like this sounds very useful in tracking a specific analysis. And if we had some workflow like you describe, then probably the only abstract guidelines we would need would be to describe how this sort of workflow should operate (e.g. that we should always meet before promoting an issue from the "partis" project column to the "CFT" project column).

Thoughts @lauradoepker @mmshipley ?

**Comment by psathyrella** [comment]
Yeah this sounds like a great idea. I like Erick's issue idea. I usually keep track of the commands I run for a project (e.g. for partis papers I'll commit a [script](https://github.com/psathyrella/partis/blob/dev/test/run-gl-inference.sh), or for running on laura's data there's this `/fh/fast/matsen_e/processed-data/partis/qa255-synth/v20/run.sh` but that's not sufficient when there's a bunch of people involved.

It seems like a good start might be for each of us to add a bit of text to the issue describing what we ran, e.g. I'd paste the second script there, more or less, and @lauradoepker and @mmshipley would add the commands (view-ascii and linearham) that they're running to get actual results that go in the paper.

**Comment by matsen** [comment]
(I'm imagining that we'd have a separate repo for this. Like `cft-analyses` or something.)

**Comment by eharkins** [comment]
@mmshipley @lauradoepker summarizing our discussion of this from this morning (let me know if I misrepresent)

We need an abstract summary of the pipeline steps, including all the different software and what it does exactly.

Also having something like @matsen describes would be important to track these steps for a given project. On that subject, Laura and Mackenzie expressed:

- it would be important to have separate records of each step of a given analysis, which doesn't lend itself as well to the idea of it all being in one issue that gets steps tacked onto it as it is promoted through analysis stages
- this would mean we would need another way to track what stage we are at for an analysis instead of what column it is currently in, since analyses would stay in their categories after completion for quick reference to answer questions like "how did we run partis for this project?"
- if using GH issues, it would be important to stay away from verbose comments on issues outside the scope of the minimum reproducible record of that analysis

**Comment by matsen** [comment]
Perhaps we'll have a chat about this in person, but having everything in one issue seems like a good thing to me, even if it gets lengthy. 

The only alternative I can think of would be to have some file we all edit with the information in it. We could consider either files in a git repo or a GitHub wiki. Those would both be nice choices.

**Comment by lauradoepker** [comment]
Here is a first draft of the flow chart.  Next steps are for @psathyrella and @eharkins to go through their respective pipelines and correct the things I've summarized, since I'm sure I've made mistakes and missed (quite a few) things.  Please include and summarize ALL steps that affect the sequences through this elaborate multigroup processing pipeline, as this is the point of this flow chart.

Please indicate where output files would exist and their general format/naming scheme, if at all possible (fastas, newicks, partis yamls, lineage graphics, etc.)

https://docs.google.com/document/d/1Q-wC_fytlPDzwQ1Up1-l_8MU7PVe0Xo1rJ2D22OlAlU/edit?usp=sharing

**Comment by eharkins** [comment]
@lauradoepker Seems like you are writing the flowchart with a perspective of how things will work going forward from now, including some things that have not been implemented yet. This makes sense that the use case for the flow chart is a map to be used by folks involved in this overall workflow going forward. Just wanted to be sure that we are on the same page that things like 

> Pipeline will choke if more than 10,000 sequences in clonal family → notify Overbaugh; shouldn’t be a problem with UMI sequencing runs

and 

> RaxML tree

are not yet a part of CFT, for example.

**Comment by lauradoepker** [comment]
Probably best to include both old and new information (with dates?).  @eharkins @psathyrella

**Comment by eharkins** [comment]
First pass ✅

**Comment by eharkins** [comment]
The document now [lives on the Matsen group wiki](https://github.com/matsengrp/wiki/wiki/BCR-Flow-Chart-Overview-of-Antibody-Lineage-Pipeline-(Overbaugh-and-Matsen-Collaboration)) so that we can track updates to it using git's version control. 

Thanks to @lauradoepker and @mmshipley for doing the bulk of the work!

Closing this issue now, but we should open a separate one if we want to implement something like what @matsen suggested above for managing the progress of an individual project through the steps outlined in our document.
