### ISSUE TITLE
Introduction on the program

### ISSUE THREAD

**Issue by xuanmingshi** [matsengrp/cft#312]
Hi all, it seems this program is proposed to make a cluster for the VDJ region of immunoglubulin. I am very curious on the application， looking forward to your help.

**Comment by metasoarous** [comment]
Hi @xuanmingshi.

This project actually doesn't do VDJ region clustering, but is a suite of tools for processing the data that comes out of https://github.com/psathyrella/partis, which _does_ do this kind of clustering.

Once you have partis clusters, you can run them through this CFT pipeline to generate clonal family trees for each of your partis clusters. This output in turn can be passed through to https://github.com/matsengrp/olmsted for clonal family navigation and tree/seq-alignment visualization.

I worked on CFT & Olmsted some years ago, but am no longer on these projects so can't provide a lot of help. But I'd recommend starting with partis to see if you can't get it running, and working your way from there. You may have better luck getting assistance if you try to get it running yourself, and ask more specific questions about any difficulties you have.

Good luck
