### ISSUE TITLE
visualizing alternative naive sequences

### ISSUE THREAD

**Issue by psathyrella** [matsengrp/cft#80]
I'm finally getting around to implementing a way to get at the uncertainty in the final naive sequence. The easy-but-probably-good-enough way I'm doing it is to look at the inferred naive sequence for sub-clusters (and super-clusters) of a sequence/cluster of interest. We already have this information lying around in the hmm cache file, since we had to calculate all these naive sequences during the course of clustering.

The probably-more-proper-but-not-necessarily-more-accurate way would be to keep track of next-most-likely paths and their probabilities within the guts of the hmm, as we do to arrive at the per-gene-support numbers. This is definitely much harder to implement, and since I think it's likely the hackey method spans a fair amount of the uncertainty, I don't have immediate plans to do it the hard way. Note that if you were interested in the uncertainty on the naive sequence for a *single* input sequence, rather than for a whole cluster, you would need to do it the hard way.

Anyway, I'm wondering how we want to visualize this. The information will be something like this:

![p](https://cloud.githubusercontent.com/assets/2960243/21403479/c728c72c-c771-11e6-89fd-bd0c98c07989.png)

where we've asked for sub/super clusters of the cluster 'a:c:d:i:b', so any clusters that have non-zero overlap with this cluster are printed. You can see they all had the same naive sequence, except for 'b', which differed by one base. Since it also decided 'b' was clonal with everybody else, and it's only one sequence so its a less accurate naive sequence inference, the true naive sequence for 'b' is probably what everybody else's was.

**Comment by metasoarous** [comment]
This has now been handled in #266.
